/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const StructureTableLazyImport = createFileRoute('/structure/table')()
const StructureGraphLazyImport = createFileRoute('/structure/graph')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const StructureTableLazyRoute = StructureTableLazyImport.update({
  id: '/structure/table',
  path: '/structure/table',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/structure/table.lazy').then((d) => d.Route),
)

const StructureGraphLazyRoute = StructureGraphLazyImport.update({
  id: '/structure/graph',
  path: '/structure/graph',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/structure/graph.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/structure/graph': {
      id: '/structure/graph'
      path: '/structure/graph'
      fullPath: '/structure/graph'
      preLoaderRoute: typeof StructureGraphLazyImport
      parentRoute: typeof rootRoute
    }
    '/structure/table': {
      id: '/structure/table'
      path: '/structure/table'
      fullPath: '/structure/table'
      preLoaderRoute: typeof StructureTableLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/structure/graph': typeof StructureGraphLazyRoute
  '/structure/table': typeof StructureTableLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/structure/graph': typeof StructureGraphLazyRoute
  '/structure/table': typeof StructureTableLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/structure/graph': typeof StructureGraphLazyRoute
  '/structure/table': typeof StructureTableLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/structure/graph' | '/structure/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/structure/graph' | '/structure/table'
  id: '__root__' | '/' | '/structure/graph' | '/structure/table'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  StructureGraphLazyRoute: typeof StructureGraphLazyRoute
  StructureTableLazyRoute: typeof StructureTableLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  StructureGraphLazyRoute: StructureGraphLazyRoute,
  StructureTableLazyRoute: StructureTableLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/structure/graph",
        "/structure/table"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/structure/graph": {
      "filePath": "structure/graph.lazy.tsx"
    },
    "/structure/table": {
      "filePath": "structure/table.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
